export const INTERESTS = [
  { name: "coding", category: "Tech & Career", emoji: "💻" },
  { name: "ui/ux design", category: "Tech & Career", emoji: "🎨" },
  { name: "graphic design", category: "Tech & Career", emoji: "🖌️" },
  { name: "startups", category: "Tech & Career", emoji: "🚀" },
  { name: "crypto", category: "Tech & Career", emoji: "🪙" },
  { name: "investing", category: "Tech & Career", emoji: "📈" },
  { name: "content creation", category: "Tech & Career", emoji: "🎥" },
  { name: "pc gaming", category: "Gaming", emoji: "⌨️" },
  { name: "console gaming", category: "Gaming", emoji: "🎮" },
  { name: "mobile gaming", category: "Gaming", emoji: "📱" },
  { name: "board games", category: "Gaming", emoji: "🎲" },
  { name: "esports", category: "Gaming", emoji: "🏆" },
  { name: "gym", category: "Sports & Fitness", emoji: "🏋️" },
  { name: "running", category: "Sports & Fitness", emoji: "🏃" },
  { name: "yoga", category: "Sports & Fitness", emoji: "🧘" },
  { name: "martial arts", category: "Sports & Fitness", emoji: "🥋" },
  { name: "cricket", category: "Sports & Fitness", emoji: "🏏" },
  { name: "football", category: "Sports & Fitness", emoji: "⚽" },
  { name: "basketball", category: "Sports & Fitness", emoji: "🏀" },
  { name: "badminton", category: "Sports & Fitness", emoji: "🏸" },
  { name: "tennis", category: "Sports & Fitness", emoji: "🎾" },
  { name: "swimming", category: "Sports & Fitness", emoji: "🏊" },
  { name: "f1", category: "Sports & Fitness", emoji: "🏎️" },
  { name: "motorcycling", category: "Sports & Fitness", emoji: "🏍️" },
  { name: "photography", category: "Arts & Creation", emoji: "📸" },
  { name: "painting", category: "Arts & Creation", emoji: "🎨" },
  { name: "digital art", category: "Arts & Creation", emoji: "📱" },
  { name: "writing", category: "Arts & Creation", emoji: "✍️" },
  { name: "diy crafting", category: "Arts & Creation", emoji: "✂️" },
  { name: "playing instruments", category: "Music", emoji: "🎸" },
  { name: "live music", category: "Music", emoji: "🎫" },
  { name: "edm", category: "Music", emoji: "🎛️" },
  { name: "hip hop", category: "Music", emoji: "🎤" },
  { name: "indie music", category: "Music", emoji: "🎧" },
  { name: "bollywood music", category: "Music", emoji: "🪘" },
  { name: "pop music", category: "Music", emoji: "🌟" },
  { name: "rock music", category: "Music", emoji: "🤘" },
  { name: "movies", category: "Entertainment", emoji: "🍿" },
  { name: "anime", category: "Entertainment", emoji: "🎌" },
  { name: "k-drama", category: "Entertainment", emoji: "🫰" },
  { name: "standup comedy", category: "Entertainment", emoji: "😂" },
  { name: "podcasts", category: "Entertainment", emoji: "🎙️" },
  { name: "memes", category: "Entertainment", emoji: "🤡" },
  { name: "cooking", category: "Lifestyle & Food", emoji: "👨‍🍳" },
  { name: "baking", category: "Lifestyle & Food", emoji: "🧁" },
  { name: "traveling", category: "Lifestyle & Food", emoji: "✈️" },
  { name: "fashion", category: "Lifestyle & Food", emoji: "👗" },
  { name: "sneakers", category: "Lifestyle & Food", emoji: "👟" },
  { name: "cafe hopping", category: "Lifestyle & Food", emoji: "☕" },
  { name: "street food", category: "Lifestyle & Food", emoji: "🌮" },
  { name: "dogs", category: "Pets", emoji: "🐕" },
  { name: "cats", category: "Pets", emoji: "🐈" },
  { name: "history", category: "Intellectual", emoji: "🏛️" },
  { name: "philosophy", category: "Intellectual", emoji: "🤔" },
  { name: "astronomy", category: "Intellectual", emoji: "🔭" },
  { name: "psychology", category: "Intellectual", emoji: "🧠" },
  { name: "reading fiction", category: "Intellectual", emoji: "📚" },
  { name: "reading nonfiction", category: "Intellectual", emoji: "📖" }
];

export const MASTER_INTERESTS_LIST = INTERESTS.map((i) => i.name);

export const VIBE_OPTIONS = ['cyber', 'nature', 'tiny', 'legendary', 'chaos'] as const;