import { VIBE_OPTIONS } from "./constants";

export interface JwtPayload {
  id:string,
  sessionId: string
}
export interface UserSession {
  userId: string;
  userProfileId: string | null;
  hasPassword: boolean
}
export enum EventType {
  // Commands
  SEND_MESSAGE = "SEND_MESSAGE",
  START_TYPING = "START_TYPING",
  STOP_TYPING = "STOP_TYPING",
  VIEW_CHAT = "VIEW_CHAT",
  LEAVE_CHAT = "LEAVE_CHAT",
  // Server Events
  NEW_MESSAGE = "NEW_MESSAGE",
  USER_TYPING = "USER_TYPING",
  USER_STOPPED_TYPING = "USER_STOPPED_TYPING",
  MESSAGE_READ = "MESSAGE_READ",
  // Global Events
  SYSTEM_EVENT = "SYSTEM_EVENT",
  MATCH_FOUND = "MATCH_FOUND",
  MATCH_EXPIRED = "MATCH_EXPIRED",
  NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE",
  FORCE_DISCONNECT = "FORCE_DISCONNECT" 
}
export enum SystemAction {
  EXTEND_REQUESTED = "EXTEND_REQUESTED",
  EXTEND_ACCEPTED = "EXTEND_ACCEPTED",
  CONVERT_REQUESTED = "CONVERT_REQUESTED",
  CONVERT_ACCEPTED = "CONVERT_ACCEPTED",
  CHAT_ENDED = "CHAT_ENDED",
  CHAT_DELETED = "CHAT_DELETED",
  UNFRIENDED = "UNFRIENDED",
  REQUEST_CANCELLED = "REQUEST_CANCELLED",
  REQUEST_ACCEPTED = "REQUEST_ACCEPTED",
  REQUEST_DECLINED = "REQUEST_DECLINED"
}
export type VibeType = typeof VIBE_OPTIONS[number];
